USE DALISA
GO
CREATE OR ALTER PROCEDURE SP_INGRESAR(@USE VARCHAR(15),@PASS VARCHAR(15))
AS
BEGIN
SELECT * FROM TBLUSUARIO  AS U 
join TBLBANCO AS B ON B.[ID BANCO] = U.[ID BANCO]
WHERE (U.[USE] =@USE AND U.[PASS]=@PASS) AND (U.ELIMINADO=0)
END
GO

CREATE OR ALTER PROCEDURE SP_CONSULTAR_USUARIO_CORREO(@CORREO VARCHAR(40))
AS
BEGIN 
SELECT * FROM TBLUSUARIO  AS u join TBLBANCO AS B ON B.[ID BANCO] = U.[ID BANCO]
WHERE  (U.ELIMINADO=0 and u.[CORREO USE] =@CORREO); 
END
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_PASSWORD_USUARIO
(@PASS VARCHAR(15),@COD VARCHAR(15))
AS
BEGIN 
BEGIN TRY  
  UPDATE TBLUSUARIO
  SET PASS=@PASS
  WHERE ([ID USUARIO]= @COD  AND ELIMINADO=0);
  SELECT 1;
END TRY  
BEGIN  CATCH  
   SELECT 0;
END CATCH  
END
GO

CREATE OR ALTER PROCEDURE SP_CONSULTAR_USUARIO(@COD VARCHAR(10),@OPC CHAR(1))
AS
BEGIN
IF @OPC = 'S'
SELECT * FROM TBLUSUARIO  AS U 
join TBLBANCO AS B ON B.[ID BANCO] = U.[ID BANCO]
join TBLSOCIO AS S ON S.[ID USUARIO] = U.[ID USUARIO]
WHERE U.[ID USUARIO]= @COD AND (U.ELIMINADO=0)
ELSE IF @OPC = 'E'
SELECT * FROM TBLUSUARIO  AS U 
join TBLBANCO AS B ON B.[ID BANCO] = U.[ID BANCO]
join TBLEMPLEADO AS E ON E.[ID USUARIO] = U.[ID USUARIO]
WHERE U.[ID USUARIO]= @COD AND (U.ELIMINADO=0)
ELSE IF @OPC='U'
SELECT * FROM TBLUSUARIO  AS U 
join TBLBANCO AS B ON B.[ID BANCO] = U.[ID BANCO]
WHERE U.[ID USUARIO]= @COD AND (U.ELIMINADO=0)
END
go



 create or alter proc SP_ACTUALIZAR_MIS_DATOS
   @idusuario varchar(10),@pais varchar(25),@Nombre varchar(25),@apellido varchar(25),@fechanaci date,@estadociv varchar(40),
  @sexo char(1), @dni char(8),@direccion varchar(105),@celular Char(9),@correo varchar(40),@idbanco int,@cuenta varchar(20)
   as
   begin
   update TBLUSUARIO set PAIS = @pais,[NOMBRE USE] = @Nombre,
   [APELLIDO USE] = @apellido, [FECHA NACI] = @fechanaci, [ESTADO CIVIL] = @estadociv,
   SEXO = @sexo, [DNI USE] = @dni, DIRECCION = @direccion,[CELULAR USE] = @celular,[CORREO USE] = @correo, [ID BANCO]=@idbanco, [CNT DEPOSITO]=@cuenta
   where [ID USUARIO]=@idusuario 
   end
   go



  

